#include "InvDB.h"
#include <string>

std::string InvDB::toString() {
   std::string retString = "";
   retString = "This is the parent specific toString test";
   return (retString);
}

void InvDB::display() {

}

void InvDB::adjustStock(Trans* trans) {

}

/**
 * AddFilm
 * Desc: adds a new film onject to the list
**/
bool InvDB::addFilm(Film* newFilm) {

   return true;
}

/**
 * isLegal
 * Desc: checks that an item exists, 
**/
bool InvDB::isLegal(std::string command) {

   return true;
}

/**
 * Int Constructor
 * Desc: uses a default size to dynamically allocate a new array
**/
InvDB::InvDB() {
   int size = 1000;
   invTable = new Film[size];
}

/**
 * Int Constructor
 * Desc: takes in a size array and dynamically allocates an array to hold
 * the film titles
 * Pre: expects size to be generated by IntenvoryController
**/
InvDB::InvDB(int size) {
   invTable = new Film[size];
}

InvDB::~InvDB() {

   if (invTable != nullptr) {
      delete invTable;
   }
}
