#include "InvDB.h"
#include "Film.h"
#include "Classic.h"
#include "Drama.h"
#include "Comedy.h"
// Necessary for file stream object handling
#include <fstream>
#include <string>



std::string InvDB::toString() {
   std::string retString = "";
   retString = "This is the parent specific toString test";
   return (retString);
}

void InvDB::display() {

}

void InvDB::adjustStock(Trans* trans) {

}


bool InvDB::contains(Film* film) {

   // search the table for the film being added to see if it's already present
   bool alreadyContainsFilm = false;
   int index = 0; 

   while (index < invTable.size()) {
      if (invTable.at(index) == *film) {
         alreadyContainsFilm = true;
         break;
      }
      else {
         index++;
      }
   }

   return alreadyContainsFilm;
}

Film* InvDB::retrieve(Film* film) {

   // search the table for the film being added to see if it's already present
   bool alreadyContainsFilm = false;
   int index = 0; 

   while (index < invTable.size()) {
      if (invTable.at(index) == *film) {
         alreadyContainsFilm = true;
         break;
      }
      else {
         index++;
      }
   }
   // index is pointing to the correct film entry at this point

   return &invTable.at(index);
}




/**
 * AddFilm
 * Desc: adds a new film onject to the list
**/
bool InvDB::addFilm(Film* film) {

   // if this is another instance of an existing Classic film, add the actor to
   // the list and increase the stock
   if (contains(film) == true && film->getGenre() == 'C') {

      int stock = retrieve(film)->getStock() + film->getStock();

      retrieve(film)->setStock(stock);
      return true;
   }
   // otherwise, if this isn't contained just add this film 
   else if (contains(film) == false) {
      invTable.push_back(*film);
      return true;
   }
   // otherwise it must be an existing non-classic film, so ignore it
   else {
      return false;
   }


}

/**
 * isLegal
 * Desc: checks that an item exists, 
**/
bool InvDB::isLegal(std::string command) {

   return true;
}







//-------|---------|---------|---------|---------|---------|---------|---------|
//
//       CONSTRUCTORS/DSTRUCTOR
//
//-------|---------|---------|---------|---------|---------|---------|---------|

/**
 * Int Constructor
 * Desc: uses a default size to dynamically allocate a new array
**/
InvDB::InvDB() {

}

/**
 * Int Constructor
 * Desc: takes in a size array and dynamically allocates an array to hold
 * the film titles
 * Pre: expects size to be generated by IntenvoryController
**/
InvDB::InvDB(std::ifstream& data) {


   while (!data.eof()) {
      // Read the next relevant line of command
      std::string filmData;
      std::getline(data, filmData);

      if (filmData.length() > 10) {
         // create borrow object and run transaction
         if (filmData.at(0) == 'F') {
            addFilm(new Comedy(filmData));
         }

         // create return object and run transaction
         else if (filmData.at(0) == 'D') {
            addFilm(new Drama(filmData));
         }

         // check customer and display history
         else if (filmData.at(0) == 'C') {
            addFilm(new Classic(filmData));
         }

         // otherwise, this is an invalid film type
         else {
            std::cerr << "Invalid film type: " << filmData.at(0) << std::endl;
         }
      }
   }
}

InvDB::~InvDB() {
   // std::cerr << "destruct invDB" << std::endl;

   // std::cerr << "end destruct invDB" << std::endl;
}
